<?php
    $product = $block->getCurrentProduct();
?>

<button class="action primary"
        id="price-request-button"
        type="submit"
        data-mage-init='{"buttonPriceRequestPopup":{}}'>
    <?php /* @escapeNotVerified */ echo __('Get the last offer'); ?>
</button>

<div id="price-request-popup-form" style="display:none;">
    <form class="form"
          action="<?php echo $block->getFormAction(); ?>"
          id="price-request-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <legend class="legend">
                <span style="font-size: 25px; font-weight: bold;">
                    <?= $block->escapeHtml(__('Ask for the latest prices and availability')) ?>
                </span>
                <div style="font-weight: bolder;">
                    <span>#<?php echo $product->getSku(); ?>:</span>
                    <span><?php echo $product->getName(); ?></span>
                </div>
            </legend>
            <br />
            <input class="no-display"
                   name="product_sku"
                   id="product_sku"
                   value="<?= $product->getSku();?>"/>
            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name"
                           id="name"
                           title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email"
                           id="email"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field comment required">
                <label class="label" for="comment"><span><?= $block->escapeHtml(__('Write us')) ?></span></label>
                <div class="control">
                    <textarea name="comment"
                              id="comment"
                              class="input-text"
                              cols="5"
                              rows="3"
                              data-validate="{required:true}"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</div>
